// constants.js
const DDRAGON = {
  versionsUrl: "https://ddragon.leagueoflegends.com/api/versions.json",
  championData: (v, locale = "fr_FR") => 
    `https://ddragon.leagueoflegends.com/cdn/${v}/data/${locale}/champion.json`,
  championDetail: (v, locale = "fr_FR") => 
    `https://ddragon.leagueoflegends.com/cdn/${v}/data/${locale}/champion/`,
  champIcon: (v, id) => 
    `https://ddragon.leagueoflegends.com/cdn/${v}/img/champion/${id}.png`,
  champSplash: (id) => 
    `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/${id}_0.jpg`
};

const GENDER_MAP = {
  'Aatrox': 'Homme', 'Ahri': 'Femme', 'Akali': 'Femme', 'Akshan': 'Homme', 'Alistar': 'Homme',
          'Amumu': 'Homme', 'Anivia': 'Femme', 'Annie': 'Femme', 'Aphelios': 'Homme', 'Ashe': 'Femme',
          'AurelionSol': 'Homme', 'Azir': 'Homme', 'Bard': 'Homme', 'Belveth': 'Femme', 'Blitzcrank': 'Homme',
          'Brand': 'Homme', 'Braum': 'Homme', 'Briar': 'Femme', 'Caitlyn': 'Femme', 'Camille': 'Femme',
          'Cassiopeia': 'Femme', 'Chogath': 'Homme', 'Corki': 'Homme', 'Darius': 'Homme', 'Diana': 'Femme',
          'Draven': 'Homme', 'DrMundo': 'Homme', 'Ekko': 'Homme', 'Elise': 'Femme', 'Evelynn': 'Femme',
          'Ezreal': 'Homme', 'Fiddlesticks': 'Autre', 'Fiora': 'Femme', 'Fizz': 'Homme', 'Galio': 'Homme',
          'Gangplank': 'Homme', 'Garen': 'Homme', 'Gnar': 'Homme', 'Gragas': 'Homme', 'Graves': 'Homme',
          'Gwen': 'Femme', 'Hecarim': 'Homme', 'Heimerdinger': 'Homme', 'Hwei': 'Homme', 'Illaoi': 'Femme',
          'Irelia': 'Femme', 'Ivern': 'Homme', 'Janna': 'Femme', 'JarvanIV': 'Homme', 'Jax': 'Homme',
          'Jayce': 'Homme', 'Jhin': 'Homme', 'Jinx': 'Femme', 'Kaisa': 'Femme', 'Kalista': 'Femme',
          'Karma': 'Femme', 'Karthus': 'Homme', 'Kassadin': 'Homme', 'Katarina': 'Femme', 'Kayle': 'Femme',
          'Kayn': 'Homme', 'Kennen': 'Homme', 'Khazix': 'Homme', 'Kindred': 'Autre', 'Kled': 'Homme',
          'KogMaw': 'Homme', 'KSante': 'Homme', 'Leblanc': 'Femme', 'LeeSin': 'Homme', 'Leona': 'Femme',
          'Lillia': 'Femme', 'Lissandra': 'Femme', 'Lucian': 'Homme', 'Lulu': 'Femme', 'Lux': 'Femme',
          'Malphite': 'Homme', 'Malzahar': 'Homme', 'Maokai': 'Homme', 'MasterYi': 'Homme', 'Milio': 'Homme',
          'MissFortune': 'Femme', 'MonkeyKing': 'Homme', 'Mordekaiser': 'Homme', 'Morgana': 'Femme', 'Naafiri': 'Femme',
          'Nami': 'Femme', 'Nasus': 'Homme', 'Nautilus': 'Homme', 'Neeko': 'Femme', 'Nidalee': 'Femme',
          'Nilah': 'Femme', 'Nocturne': 'Homme', 'Nunu': 'Homme', 'Olaf': 'Homme', 'Orianna': 'Femme',
          'Ornn': 'Homme', 'Pantheon': 'Homme', 'Poppy': 'Femme', 'Pyke': 'Homme', 'Qiyana': 'Femme',
          'Quinn': 'Femme', 'Rakan': 'Homme', 'Rammus': 'Homme', 'RekSai': 'Femme', 'Rell': 'Femme',
          'Renata': 'Femme', 'Renekton': 'Homme', 'Rengar': 'Homme', 'Riven': 'Femme', 'Rumble': 'Homme',
          'Ryze': 'Homme', 'Samira': 'Femme', 'Sejuani': 'Femme', 'Senna': 'Femme', 'Seraphine': 'Femme',
          'Sett': 'Homme', 'Shaco': 'Homme', 'Shen': 'Homme', 'Shyvana': 'Femme', 'Singed': 'Homme',
          'Sion': 'Homme', 'Sivir': 'Femme', 'Skarner': 'Homme', 'Smolder': 'Homme', 'Sona': 'Femme',
          'Soraka': 'Femme', 'Swain': 'Homme', 'Sylas': 'Homme', 'Syndra': 'Femme', 'TahmKench': 'Homme',
          'Taliyah': 'Femme', 'Talon': 'Homme', 'Taric': 'Homme', 'Teemo': 'Homme', 'Thresh': 'Homme',
          'Tristana': 'Femme', 'Trundle': 'Homme', 'Tryndamere': 'Homme', 'TwistedFate': 'Homme', 'Twitch': 'Homme',
          'Udyr': 'Homme', 'Urgot': 'Homme', 'Varus': 'Homme', 'Vayne': 'Femme', 'Veigar': 'Homme',
          'Velkoz': 'Homme', 'Vex': 'Femme', 'Vi': 'Femme', 'Viego': 'Homme', 'Viktor': 'Homme',
          'Vladimir': 'Homme', 'Volibear': 'Homme', 'Warwick': 'Homme', 'Xayah': 'Femme', 'Xerath': 'Homme',
          'XinZhao': 'Homme', 'Yasuo': 'Homme', 'Yone': 'Homme', 'Yorick': 'Homme', 'Yuumi': 'Femme',
          'Zac': 'Homme', 'Zed': 'Homme', 'Zeri': 'Femme', 'Ziggs': 'Homme', 'Zilean': 'Homme',
          'Zoe': 'Femme', 'Zyra': 'Femme'
        };

const POSITION_MAP = {
  'Aatrox': 'Top', 'Ahri': 'Mid', 'Akali': 'Mid', 'Akshan': 'Mid', 'Alistar': 'Support',
          'Amumu': 'Jungle', 'Anivia': 'Mid', 'Annie': 'Mid', 'Aphelios': 'ADC', 'Ashe': 'ADC',
          'AurelionSol': 'Mid', 'Azir': 'Mid', 'Bard': 'Support', 'Belveth': 'Jungle', 'Blitzcrank': 'Support',
          'Brand': 'Support', 'Braum': 'Support', 'Briar': 'Jungle', 'Caitlyn': 'ADC', 'Camille': 'Top',
          'Cassiopeia': 'Mid', 'Chogath': 'Top', 'Corki': 'ADC', 'Darius': 'Top', 'Diana': 'Jungle',
          'Draven': 'ADC', 'DrMundo': 'Top', 'Ekko': 'Jungle', 'Elise': 'Jungle', 'Evelynn': 'Jungle',
          'Ezreal': 'ADC', 'Fiddlesticks': 'Jungle', 'Fiora': 'Top', 'Fizz': 'Mid', 'Galio': 'Mid',
          'Gangplank': 'Top', 'Garen': 'Top', 'Gnar': 'Top', 'Gragas': 'Jungle', 'Graves': 'Jungle',
          'Gwen': 'Top', 'Hecarim': 'Jungle', 'Heimerdinger': 'Mid', 'Hwei': 'Mid', 'Illaoi': 'Top',
          'Irelia': 'Top', 'Ivern': 'Jungle', 'Janna': 'Support', 'JarvanIV': 'Jungle', 'Jax': 'Top',
          'Jayce': 'Top', 'Jhin': 'ADC', 'Jinx': 'ADC', 'Kaisa': 'ADC', 'Kalista': 'ADC',
          'Karma': 'Support', 'Karthus': 'Jungle', 'Kassadin': 'Mid', 'Katarina': 'Mid', 'Kayle': 'Top',
          'Kayn': 'Jungle', 'Kennen': 'Top', 'Khazix': 'Jungle', 'Kindred': 'Jungle', 'Kled': 'Top',
          'KogMaw': 'ADC', 'KSante': 'Top', 'Leblanc': 'Mid', 'LeeSin': 'Jungle', 'Leona': 'Support',
          'Lillia': 'Jungle', 'Lissandra': 'Mid', 'Lucian': 'ADC', 'Lulu': 'Support', 'Lux': 'Support',
          'Malphite': 'Top', 'Malzahar': 'Mid', 'Maokai': 'Support', 'MasterYi': 'Jungle', 'Milio': 'Support',
          'MissFortune': 'ADC', 'MonkeyKing': 'Top', 'Mordekaiser': 'Top', 'Morgana': 'Support', 'Naafiri': 'Mid',
          'Nami': 'Support', 'Nasus': 'Top', 'Nautilus': 'Support', 'Neeko': 'Mid', 'Nidalee': 'Jungle',
          'Nilah': 'ADC', 'Nocturne': 'Jungle', 'Nunu': 'Jungle', 'Olaf': 'Jungle', 'Orianna': 'Mid',
          'Ornn': 'Top', 'Pantheon': 'Support', 'Poppy': 'Jungle', 'Pyke': 'Support', 'Qiyana': 'Jungle',
          'Quinn': 'Top', 'Rakan': 'Support', 'Rammus': 'Jungle', 'RekSai': 'Jungle', 'Rell': 'Support',
          'Renata': 'Support', 'Renekton': 'Top', 'Rengar': 'Jungle', 'Riven': 'Top', 'Rumble': 'Top',
          'Ryze': 'Mid', 'Samira': 'ADC', 'Sejuani': 'Jungle', 'Senna': 'Support', 'Seraphine': 'Support',
          'Sett': 'Top', 'Shaco': 'Jungle', 'Shen': 'Top', 'Shyvana': 'Jungle', 'Singed': 'Top',
          'Sion': 'Top', 'Sivir': 'ADC', 'Skarner': 'Jungle', 'Smolder': 'ADC', 'Sona': 'Support',
          'Soraka': 'Support', 'Swain': 'Support', 'Sylas': 'Mid', 'Syndra': 'Mid', 'TahmKench': 'Support',
          'Taliyah': 'Jungle', 'Talon': 'Mid', 'Taric': 'Support', 'Teemo': 'Top', 'Thresh': 'Support',
          'Tristana': 'ADC', 'Trundle': 'Top', 'Tryndamere': 'Top', 'TwistedFate': 'Mid', 'Twitch': 'ADC',
          'Udyr': 'Jungle', 'Urgot': 'Top', 'Varus': 'ADC', 'Vayne': 'ADC', 'Veigar': 'Mid',
          'Velkoz': 'Support', 'Vex': 'Mid', 'Vi': 'Jungle', 'Viego': 'Jungle', 'Viktor': 'Mid',
          'Vladimir': 'Mid', 'Volibear': 'Jungle', 'Warwick': 'Jungle', 'Xayah': 'ADC', 'Xerath': 'Support',
          'XinZhao': 'Jungle', 'Yasuo': 'Mid', 'Yone': 'Mid', 'Yorick': 'Top', 'Yuumi': 'Support',
          'Zac': 'Jungle', 'Zed': 'Mid', 'Zeri': 'ADC', 'Ziggs': 'Mid', 'Zilean': 'Support',
          'Zoe': 'Mid', 'Zyra': 'Support'
};

const REGION_MAP = {
 'Aatrox': 'Shurima', 'Ahri': 'Ionia', 'Akali': 'Ionia', 'Akshan': 'Shurima', 'Alistar': 'Noxus',
          'Amumu': 'Shurima', 'Anivia': 'Freljord', 'Annie': 'Noxus', 'Aphelios': 'Targon', 'Ashe': 'Freljord',
          'AurelionSol': 'Targon', 'Azir': 'Shurima', 'Bard': 'Runeterra', 'Belveth': 'Void', 'Blitzcrank': 'Zaun',
          'Brand': 'Runeterra', 'Braum': 'Freljord', 'Briar': 'Noxus', 'Caitlyn': 'Piltover', 'Camille': 'Piltover',
          'Cassiopeia': 'Noxus', 'Chogath': 'Void', 'Corki': 'Bandle', 'Darius': 'Noxus', 'Diana': 'Targon',
          'Draven': 'Noxus', 'DrMundo': 'Zaun', 'Ekko': 'Zaun', 'Elise': 'Noxus', 'Evelynn': 'Runeterra',
          'Ezreal': 'Piltover', 'Fiddlesticks': 'Runeterra', 'Fiora': 'Demacia', 'Fizz': 'Bilgewater', 'Galio': 'Demacia',
          'Gangplank': 'Bilgewater', 'Garen': 'Demacia', 'Gnar': 'Freljord', 'Gragas': 'Freljord', 'Graves': 'Bilgewater',
          'Gwen': 'Îles Obscures', 'Hecarim': 'Îles Obscures', 'Heimerdinger': 'Piltover', 'Hwei': 'Ionia', 'Illaoi': 'Bilgewater',
          'Irelia': 'Ionia', 'Ivern': 'Ionia', 'Janna': 'Zaun', 'JarvanIV': 'Demacia', 'Jax': 'Icathia',
          'Jayce': 'Piltover', 'Jhin': 'Ionia', 'Jinx': 'Zaun', 'Kaisa': 'Void', 'Kalista': 'Îles Obscures',
          'Karma': 'Ionia', 'Karthus': 'Îles Obscures', 'Kassadin': 'Void', 'Katarina': 'Noxus', 'Kayle': 'Demacia',
          'Kayn': 'Ionia', 'Kennen': 'Ionia', 'Khazix': 'Void', 'Kindred': 'Runeterra', 'Kled': 'Noxus',
          'KogMaw': 'Void', 'KSante': 'Nazumah', 'Leblanc': 'Noxus', 'LeeSin': 'Ionia', 'Leona': 'Targon',
          'Lillia': 'Ionia', 'Lissandra': 'Freljord', 'Lucian': 'Demacia', 'Lulu': 'Bandle', 'Lux': 'Demacia',
          'Malphite': 'Ixtal', 'Malzahar': 'Void', 'Maokai': 'Îles Obscures', 'MasterYi': 'Ionia', 'Milio': 'Ixtal',
          'MissFortune': 'Bilgewater', 'MonkeyKing': 'Ionia', 'Mordekaiser': 'Noxus', 'Morgana': 'Demacia', 'Naafiri': 'Shurima',
          'Nami': 'Bilgewater', 'Nasus': 'Shurima', 'Nautilus': 'Bilgewater', 'Neeko': 'Ixtal', 'Nidalee': 'Ixtal',
          'Nilah': 'Bilgewater', 'Nocturne': 'Runeterra', 'Nunu': 'Freljord', 'Olaf': 'Freljord', 'Orianna': 'Piltover',
          'Ornn': 'Freljord', 'Pantheon': 'Targon', 'Poppy': 'Demacia', 'Pyke': 'Bilgewater', 'Qiyana': 'Ixtal',
          'Quinn': 'Demacia', 'Rakan': 'Ionia', 'Rammus': 'Shurima', 'RekSai': 'Void', 'Rell': 'Noxus',
          'Renata': 'Zaun', 'Renekton': 'Shurima', 'Rengar': 'Ixtal', 'Riven': 'Noxus', 'Rumble': 'Bandle',
          'Ryze': 'Runeterra', 'Samira': 'Noxus', 'Sejuani': 'Freljord', 'Senna': 'Demacia', 'Seraphine': 'Piltover',
          'Sett': 'Ionia', 'Shaco': 'Runeterra', 'Shen': 'Ionia', 'Shyvana': 'Demacia', 'Singed': 'Zaun',
          'Sion': 'Noxus', 'Sivir': 'Shurima', 'Skarner': 'Ixtal', 'Smolder': 'Camavor', 'Sona': 'Demacia',
          'Soraka': 'Targon', 'Swain': 'Noxus', 'Sylas': 'Demacia', 'Syndra': 'Ionia', 'TahmKench': 'Bilgewater',
          'Taliyah': 'Shurima', 'Talon': 'Noxus', 'Taric': 'Targon', 'Teemo': 'Bandle', 'Thresh': 'Îles Obscures',
          'Tristana': 'Bandle', 'Trundle': 'Freljord', 'Tryndamere': 'Freljord', 'TwistedFate': 'Bilgewater', 'Twitch': 'Zaun',
          'Udyr': 'Freljord', 'Urgot': 'Zaun', 'Varus': 'Ionia', 'Vayne': 'Demacia', 'Veigar': 'Bandle',
          'Velkoz': 'Void', 'Vex': 'Îles Obscures', 'Vi': 'Piltover', 'Viego': 'Camavor', 'Viktor': 'Zaun',
          'Vladimir': 'Noxus', 'Volibear': 'Freljord', 'Warwick': 'Zaun', 'Xayah': 'Ionia', 'Xerath': 'Shurima',
          'XinZhao': 'Demacia', 'Yasuo': 'Ionia', 'Yone': 'Ionia', 'Yorick': 'Îles Obscures', 'Yuumi': 'Bandle',
          'Zac': 'Zaun', 'Zed': 'Ionia', 'Zeri': 'Zaun', 'Ziggs': 'Zaun', 'Zilean': 'Icathia',
          'Zoe': 'Targon', 'Zyra': 'Ixtal'
};

const SPECIES_MAP = {
  'Aatrox': 'Darkin',
  'Ahri': 'Vastaya',
  'Akali': 'Humain',
  'Akshan': 'Humain',
  'Alistar': 'Minotaure',
  'Amumu': 'Yordle',
  'Anivia': 'Demi-dieu',
  'Annie': 'Humain',
  'Aphelios': 'Humain',
  'Ashe': 'Humain',
  'AurelionSol': 'Dragon céleste',
  'Azir': 'Dieu-empereur',
  'Bard': 'Céleste',
  'Belveth': 'Vide',
  'Blitzcrank': 'Golem',
  'Brand': 'Humain',
  'Braum': 'Humain',
  'Briar': 'Vampire',
  'Caitlyn': 'Humain',
  'Camille': 'Humain',
  'Cassiopeia': 'Humain',
  'Chogath': 'Vide',
  'Corki': 'Yordle',
  'Darius': 'Humain',
  'Diana': 'Humain',
  'Draven': 'Humain',
  'DrMundo': 'Humain',
  'Ekko': 'Humain',
  'Elise': 'Humain',
  'Evelynn': 'Démon',
  'Ezreal': 'Humain',
  'Fiddlesticks': 'Démon',
  'Fiora': 'Humain',
  'Fizz': 'Yordle',
  'Galio': 'Golem',
  'Gangplank': 'Humain',
  'Garen': 'Humain',
  'Gnar': 'Yordle',
  'Gragas': 'Humain',
  'Graves': 'Humain',
  'Gwen': 'Poupée',
  'Hecarim': 'Revenant',
  'Heimerdinger': 'Yordle',
  'Hwei': 'Humain',
  'Illaoi': 'Humain',
  'Irelia': 'Humain',
  'Ivern': 'Humain',
  'Janna': 'Demi-dieu',
  'JarvanIV': 'Humain',
  'Jax': 'Humain',
  'Jayce': 'Humain',
  'Jhin': 'Humain',
  'Jinx': 'Humain',
  'Kaisa': 'Humain',
  'Kalista': 'Revenant',
  'Karma': 'Humain',
  'Karthus': 'Liche',
  'Kassadin': 'Humain',
  'Katarina': 'Humain',
  'Kayle': 'Aspect',
  'Kayn': 'Humain',
  'Kennen': 'Yordle',
  'Khazix': 'Vide',
  'Kindred': 'Demi-dieu',
  'Kled': 'Yordle',
  'KogMaw': 'Vide',
  'KSante': 'Humain',
  'Leblanc': 'Humain',
  'LeeSin': 'Humain',
  'Leona': 'Humain',
  'Lillia': 'Rêve',
  'Lissandra': 'Humain',
  'Lucian': 'Humain',
  'Lulu': 'Yordle',
  'Lux': 'Humain',
  'Malphite': 'Golem',
  'Malzahar': 'Humain',
  'Maokai': 'Tréant',
  'MasterYi': 'Humain',
  'Milio': 'Humain',
  'MissFortune': 'Humain',
  'MonkeyKing': 'Vastaya',
  'Mordekaiser': 'Revenant',
  'Morgana': 'Aspect',
  'Naafiri': 'Darkin',
  'Nami': 'Vastaya',
  'Nasus': 'Dieu-empereur',
  'Nautilus': 'Revenant',
  'Neeko': 'Vastaya',
  'Nidalee': 'Humain',
  'Nilah': 'Humain',
  'Nocturne': 'Démon',
  'Nunu': 'Humain',
  'Olaf': 'Humain',
  'Orianna': 'Golem',
  'Ornn': 'Demi-dieu',
  'Pantheon': 'Aspect',
  'Poppy': 'Yordle',
  'Pyke': 'Revenant',
  'Qiyana': 'Humain',
  'Quinn': 'Humain',
  'Rakan': 'Vastaya',
  'Rammus': 'Dieu-empereur',
  'RekSai': 'Vide',
  'Rell': 'Humain',
  'Renata': 'Humain',
  'Renekton': 'Dieu-empereur',
  'Rengar': 'Vastaya',
  'Riven': 'Humain',
  'Rumble': 'Yordle',
  'Ryze': 'Humain',
  'Samira': 'Humain',
  'Sejuani': 'Humain',
  'Senna': 'Humain',
  'Seraphine': 'Humain',
  'Sett': 'Vastaya',
  'Shaco': 'Démon',
  'Shen': 'Humain',
  'Shyvana': 'Dragon',
  'Singed': 'Humain',
  'Sion': 'Revenant',
  'Sivir': 'Humain',
  'Skarner': 'Brakern',
  'Smolder': 'Dragon',  'Sona': 'Humain',  'Soraka': 'Céleste',  'Swain': 'Humain',  'Sylas': 'Humain',  'Syndra': 'Humain',  'TahmKench': 'Démon',
  'Taliyah': 'Humain',  'Talon': 'Humain',
  'Taric': 'Humain',  'Teemo': 'Yordle',  'Thresh': 'Revenant',  'Tristana': 'Yordle',  'Trundle': 'Troll','Tryndamere': 'Humain','TwistedFate': 'Humain','Twitch': 'Rat','Udyr': 'Humain',
  'Urgot': 'Humain','Varus': 'Darkin','Vayne': 'Humain',
  'Veigar': 'Yordle','Velkoz': 'Vide','Vex': 'Yordle','Vi': 'Humain',
  'Viego': 'Revenant','Viktor': 'Humain','Vladimir': 'Vampire',
  'Volibear': 'Demi-dieu','Warwick': 'Chimère','Xayah': 'Vastaya',
  'Xerath': 'Dieu-empereur','XinZhao': 'Humain',
  'Yasuo': 'Humain',
  'Yone': 'Humain',  'Yorick': 'Humain',  'Yuumi': 'Chat magique',  'Zac': 'Golem',  'Zed': 'Humain',  'Zeri': 'Humain',
  'Ziggs': 'Yordle',  'Zilean': 'Humain',  'Zoe': 'Aspect', 'Zyra': 'Plante',
};

const YEAR_MAP = {
  'Alistar': 2009, 'Annie': 2009, 'Ashe': 2009, 'Fiddlesticks': 2009, 'Jax': 2009,
          'Kayle': 2009, 'MasterYi': 2009, 'Morgana': 2009, 'Nunu': 2009, 'Ryze': 2009,
          'Sion': 2009, 'Sivir': 2009, 'Soraka': 2009, 'Teemo': 2009, 'Tristana': 2009,
          'TwistedFate': 2009, 'Warwick': 2009, 'Singed': 2009, 'Zilean': 2009, 'Evelynn': 2009,
          'Twitch': 2009, 'Karthus': 2009, 'Amumu': 2009, 'Chogath': 2009, 'Anivia': 2009,
          'Rammus': 2009, 'Veigar': 2009, 'Kassadin': 2009, 'Gangplank': 2009, 'Taric': 2009,
          'Blitzcrank': 2009, 'DrMundo': 2009, 'Shen': 2009, 'Akali': 2010, 'Kennen': 2010,
          'Garen': 2010, 'Pantheon': 2010, 'Malphite': 2010, 'Mordekaiser': 2010, 'Ezreal': 2010,
          'Heimerdinger': 2010, 'Katarina': 2010, 'Olaf': 2010, 'Corki': 2010, 'Nidalee': 2010,
          'Poppy': 2010, 'Gragas': 2010, 'Vladimir': 2010, 'Urgot': 2010, 'MissFortune': 2010,
          'KogMaw': 2010, 'Xin Zhao': 2010, 'Lux': 2010, 'Leblanc': 2010, 'Irelia': 2010,
          'Trundle': 2010, 'Cassiopeia': 2010, 'Galio': 2010, 'Renekton': 2010, 'Karma': 2011,
          'Maokai': 2011, 'Jarvan IV': 2011, 'Nocturne': 2011, 'Brand': 2011, 'Lee Sin': 2011,
          'Rumble': 2011, 'Vayne': 2011, 'Orianna': 2011, 'Yorick': 2011, 'Leona': 2011,
          'Wukong': 2011, 'Skarner': 2011, 'Talon': 2011, 'Riven': 2011, 'Xerath': 2011,
          'Graves': 2011, 'Shyvana': 2011, 'Fizz': 2011, 'Volibear': 2011, 'Ahri': 2011,
          'Viktor': 2011, 'Sejuani': 2012, 'Ziggs': 2012, 'Nautilus': 2012, 'Fiora': 2012,
          'Lulu': 2012, 'Hecarim': 2012, 'Varus': 2012, 'Darius': 2012, 'Draven': 2012,
          'Jayce': 2012, 'Zyra': 2012, 'Diana': 2012, 'Rengar': 2012, 'Syndra': 2012,
          'Kha\'Zix': 2012, 'Elise': 2012, 'Zed': 2012, 'Nami': 2012, 'Vi': 2012,
          'Thresh': 2013, 'Quinn': 2013, 'Zac': 2013, 'Lissandra': 2013, 'Aatrox': 2013,
          'Lucian': 2013, 'Jinx': 2013, 'Yasuo': 2013, 'Vel\'Koz': 2014, 'Braum': 2014,
          'Gnar': 2014, 'Azir': 2014, 'Kalista': 2014, 'Rek\'Sai': 2014, 'Bard': 2015,
          'Ekko': 2015, 'Tahm Kench': 2015, 'Kindred': 2015, 'Illaoi': 2015, 'Jhin': 2016,
          'Aurelion Sol': 2016, 'Taliyah': 2016, 'Kled': 2016, 'Ivern': 2016, 'Camille': 2016,
          'Xayah': 2017, 'Rakan': 2017, 'Kayn': 2017, 'Ornn': 2017, 'Zoe': 2017,
          'Kai\'Sa': 2018, 'Pyke': 2018, 'Neeko': 2018, 'Sylas': 2019, 'Yuumi': 2019,
          'Qiyana': 2019, 'Senna': 2019, 'Aphelios': 2019, 'Sett': 2020, 'Lillia': 2020,
          'Yone': 2020, 'Samira': 2020, 'Seraphine': 2020, 'Rell': 2020, 'Viego': 2021,
          'Gwen': 2021, 'Akshan': 2021, 'Vex': 2021, 'Zeri': 2022, 'Renata': 2022,
          'Bel\'Veth': 2022, 'Nilah': 2022, 'K\'Sante': 2022, 'Milio': 2023, 'Naafiri': 2023,
          'Briar': 2023, 'Hwei': 2023, 'Smolder': 2024
};